-- database/functions/numeracion.sql — Placeholder para numeración (se llenará en módulo 01)
-- Aquí irán funciones para:
-- - siguiente cliente_id (>=100)
-- - referencia expediente {ADUANA}-{#####}-{AÑO}
